name: 'BUMP VERSION'
on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  merge_pr:
    name: 'PR Merged'
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_ORG_PAT }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Git config
        run: |
          git config --global user.email "${{ secrets.GH_ORG_EMAIL }}"
          git config --global user.name "${{ secrets.GH_ORG_NAME }}"
      - name: Apply version bump (patch)
        uses: borales/actions-yarn@v4
        with: 
          cmd: version --patch
      - name: Git push version bump
        run: git push origin master --follow-tags --force
